### ISSUE TITLE
No errors when using the action

### ISSUE THREAD

**Issue by aqabawe** [cclauss/GitHub-Action-for-Flake8#1]
Hello,

I have the following action defined in my repo:
```
name: CI/CD
on: [push, pull_request]
jobs:
  flake8-lint:
    runs-on: self-hosted
    name: Lint
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for Flake8
      uses: cclauss/GitHub-Action-for-Flake8@master
      with:
        args: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
```

The output when this action runs is 
```
#########################################
Starting CI/CD:cclaussGitHub-Action-for-Flake8
0
#########################################
Completed CI/CD:cclaussGitHub-Action-for-Flake8
```

The thing is when I run `flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics` locally in the repo, I get 3 warnings. How come there's a difference, am I doing something wrong? I get the same result when using `ubuntu-latest` instead of the self-hosted runner.
